# Generated by Django 3.2.9 on 2021-11-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('source_product', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('retailer', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
