# Generated by Django 3.2.9 on 2021-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('source_product', models.CharField(max_length=64)),
                ('product', models.CharField(max_length=64)),
                ('retailer', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('API_KEY', models.CharField(max_length=64)),
                ('requests', models.IntegerField()),
                ('flagged_requests', models.IntegerField()),
                ('to_be_billed', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
        ),
        migrations.DeleteModel(
            name='results',
        ),
    ]
