# Generated by Django 3.2.9 on 2021-11-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_auto_20211115_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_search_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('number_searches_run', models.IntegerField()),
                ('number_of_searches_completed', models.IntegerField()),
                ('number_of_results', models.IntegerField()),
            ],
        ),
    ]
